name    = "Gruvbox Dark"
variant = "dark"

[palette]
base      = "#282828"
mantle    = "#1d2021"
crust     = "#181818"

surface0  = "#32302f"
surface1  = "#3c3836"
surface2  = "#504945"

text      = "#ebdbb2"
subtext1  = "#d5c4a1"
subtext0  = "#bdae93"

primary   = "#d3869b"
secondary = "#83a598"
tertiary  = "#b8bb26"
error     = "#fb4934"
warning   = "#fabd2f"
info      = "#8ec07c"

overlay0  = "#665c54"
overlay1  = "#7c6f64"
overlay2  = "#928374"
