name    = "Tokyo Night Storm"
variant = "dark"

[palette]
base      = "#24283b"
mantle    = "#1f2335"
crust     = "#1a1b26"

surface0  = "#292e42"
surface1  = "#2f354a"
surface2  = "#3b4261"

text      = "#c0caf5"
subtext1  = "#a9b1d6"
subtext0  = "#9aa5ce"

primary   = "#bb9af7"
secondary = "#7aa2f7"
tertiary  = "#9ece6a"
error     = "#f7768e"
warning   = "#ff9e64"
info      = "#2ac3de"

overlay0  = "#565f89"
overlay1  = "#636d97"
overlay2  = "#737aa2"
