/// writers/ghostty.rs
///
/// Writes a Ghostty theme file from the resolved palette.
///
/// Output: ~/.config/ghostty/themes/crawl
///
/// Wire it into your Ghostty config:
///   # ~/.config/ghostty/config
///   theme = crawl
///
/// The theme reloads automatically when Ghostty detects the file change
/// (Ghostty watches its config and theme files via inotify).
///
/// ANSI 16-color mapping:
///   Ghostty uses palette = 0..15 for the 16 ANSI terminal colors.
///   We map crawl's semantic roles onto the standard ANSI positions so
///   that terminal apps (ls, bat, delta, etc.) look coherent.
///
///   0  black         → surface1   (used as black in most palettes)
///   1  red           → error
///   2  green         → tertiary
///   3  yellow        → warning
///   4  blue          → secondary
///   5  magenta       → primary
///   6  cyan          → info
///   7  white         → subtext1
///   8  bright black  → overlay1   (grey)
///   9  bright red    → error      (same, slightly brighter — adjust if desired)
///   10 bright green  → tertiary
///   11 bright yellow → warning
///   12 bright blue   → secondary
///   13 bright magenta→ primary
///   14 bright cyan   → info
///   15 bright white  → text

use crate::{palette::Palette, ThemeError};
use tracing::info;

pub async fn write(palette: &Palette) -> Result<(), ThemeError> {
    let content = render(palette);

    let themes_dir = dirs::config_dir()
        .ok_or_else(|| ThemeError::Writer("cannot determine config dir".into()))?
        .join("ghostty")
        .join("themes");

    tokio::fs::create_dir_all(&themes_dir).await?;

    let path = themes_dir.join("crawl");
    tokio::fs::write(&path, content).await?;

    info!("ghostty: theme written to {:?}", path);
    Ok(())
}

fn render(p: &Palette) -> String {
    format!(
r#"# Generated by crawl-theme — do not edit manually.
# Source: crawl theme engine — edit via `crawl theme --set` or `crawl theme --wallpaper`.

# ── Core colors ────────────────────────────────────────────────────────────────
background = {base}
foreground = {text}

# Cursor
cursor-color = {primary}
cursor-text   = {base}

# Selection
selection-background = {surface2}
selection-foreground = {text}

# ── 16-color ANSI palette ──────────────────────────────────────────────────────
# Normal colors (0–7)
palette = 0=#{surface1}
palette = 1=#{error}
palette = 2=#{tertiary}
palette = 3=#{warning}
palette = 4=#{secondary}
palette = 5=#{primary}
palette = 6=#{info}
palette = 7=#{subtext1}

# Bright colors (8–15)
palette = 8=#{overlay1}
palette = 9=#{error}
palette = 10=#{tertiary}
palette = 11=#{warning}
palette = 12=#{secondary}
palette = 13=#{primary}
palette = 14=#{info}
palette = 15=#{text}
"#,
        base      = p.base,
        text      = p.text,
        primary   = p.primary,
        secondary = p.secondary,
        tertiary  = p.tertiary,
        error     = p.error,
        warning   = p.warning,
        info      = p.info,
        surface1  = p.surface1.trim_start_matches('#'),
        surface2  = p.surface2.trim_start_matches('#'),
        subtext1  = p.subtext1.trim_start_matches('#'),
        overlay1  = p.overlay1.trim_start_matches('#'),
    )
}
