/// writers/gtk.rs
///
/// Writes crawl's resolved palette as CSS custom properties for GTK3 and GTK4.
///
/// GTK3: ~/.config/gtk-3.0/colors.css   (imported by gtk.css)
/// GTK4: ~/.config/gtk-4.0/colors.css   (imported by gtk.css)
///
/// How to wire this into your GTK config:
///
///   GTK4: ~/.config/gtk-4.0/gtk.css
///   ─────────────────────────────────
///   @import 'colors.css';
///
///   /* override theme tokens using crawl vars */
///   @define-color accent_color @crawl_primary;
///   @define-color window_bg_color @crawl_base;
///   @define-color window_fg_color @crawl_text;
///   @define-color headerbar_bg_color @crawl_mantle;
///   @define-color headerbar_fg_color @crawl_text;
///   @define-color view_bg_color @crawl_surface0;
///   @define-color view_fg_color @crawl_text;
///   @define-color card_bg_color @crawl_surface1;
///   @define-color popover_bg_color @crawl_surface0;
///   @define-color dialog_bg_color @crawl_surface1;
///   @define-color sidebar_bg_color @crawl_mantle;
///   @define-color error_color @crawl_error;
///   @define-color warning_color @crawl_warning;
///   @define-color success_color @crawl_tertiary;
///
///   GTK3: ~/.config/gtk-3.0/gtk.css
///   ─────────────────────────────────
///   @import 'colors.css';
///
///   /* GTK3 doesn't have as many standardised tokens */
///   /* Use Adwaita as base theme + crawl for overrides */

use crate::{palette::Palette, ThemeError};
use tracing::info;

pub async fn write(palette: &Palette) -> Result<(), ThemeError> {
    let css = render(palette);

    write_to("gtk-4.0", &css).await?;
    write_to("gtk-3.0", &css).await?;

    info!("gtk: colors.css written for gtk-3.0 and gtk-4.0");
    Ok(())
}

fn render(p: &Palette) -> String {
    // We define @crawl_* names alongside GTK4's own @define-color names
    // so your gtk.css can reference either.
    format!(
r#"/* Generated by crawl-theme — do not edit manually */
/* Regenerated on every theme change. Edit ~/.config/crawl/crawl.toml to change themes. */

/* ── crawl semantic roles ──────────────────────────────────────────────────── */
@define-color crawl_base      {base};
@define-color crawl_mantle    {mantle};
@define-color crawl_crust     {crust};
@define-color crawl_surface0  {surface0};
@define-color crawl_surface1  {surface1};
@define-color crawl_surface2  {surface2};
@define-color crawl_text      {text};
@define-color crawl_subtext1  {subtext1};
@define-color crawl_subtext0  {subtext0};
@define-color crawl_primary   {primary};
@define-color crawl_secondary {secondary};
@define-color crawl_tertiary  {tertiary};
@define-color crawl_error     {error};
@define-color crawl_warning   {warning};
@define-color crawl_info      {info};
@define-color crawl_overlay0  {overlay0};
@define-color crawl_overlay1  {overlay1};
@define-color crawl_overlay2  {overlay2};

/* ── GTK4 / libadwaita standard color tokens ───────────────────────────────── */
/* These map crawl roles onto Adwaita's expected names so GTK4 apps             */
/* automatically pick up the theme without per-app configuration.               */
@define-color accent_color            {primary};
@define-color accent_bg_color         {primary};
@define-color accent_fg_color         {base};

@define-color window_bg_color         {base};
@define-color window_fg_color         {text};

@define-color view_bg_color           {surface0};
@define-color view_fg_color           {text};

@define-color headerbar_bg_color      {mantle};
@define-color headerbar_fg_color      {text};
@define-color headerbar_border_color  {surface1};
@define-color headerbar_backdrop_color {mantle};
@define-color headerbar_shade_color   {crust};

@define-color card_bg_color           {surface0};
@define-color card_fg_color           {text};
@define-color card_shade_color        {surface1};

@define-color dialog_bg_color         {surface1};
@define-color dialog_fg_color         {text};

@define-color popover_bg_color        {surface0};
@define-color popover_fg_color        {text};
@define-color popover_shade_color     {surface1};

@define-color sidebar_bg_color        {mantle};
@define-color sidebar_fg_color        {text};
@define-color sidebar_backdrop_color  {mantle};
@define-color sidebar_shade_color     {crust};
@define-color sidebar_border_color    {surface1};

@define-color thumbnail_bg_color      {surface0};
@define-color thumbnail_fg_color      {text};

/* Status colours */
@define-color error_color             {error};
@define-color error_bg_color          {error};
@define-color error_fg_color          {base};
@define-color warning_color           {warning};
@define-color warning_bg_color        {warning};
@define-color warning_fg_color        {base};
@define-color success_color           {tertiary};
@define-color success_bg_color        {tertiary};
@define-color success_fg_color        {base};
@define-color destructive_color       {error};
@define-color destructive_bg_color    {error};
@define-color destructive_fg_color    {base};

/* Borders and separators */
@define-color borders                 {surface1};
@define-color shade_color             {surface0};

/* ── GTK3 named colors ─────────────────────────────────────────────────────── */
/* GTK3 apps that query these names directly */
@define-color theme_base_color        {base};
@define-color theme_bg_color          {mantle};
@define-color theme_fg_color          {text};
@define-color theme_text_color        {text};
@define-color theme_selected_bg_color {primary};
@define-color theme_selected_fg_color {base};
@define-color theme_tooltip_bg_color  {surface1};
@define-color theme_tooltip_fg_color  {text};
@define-color insensitive_bg_color    {surface0};
@define-color insensitive_fg_color    {overlay0};
@define-color insensitive_base_color  {surface0};
@define-color link_color              {secondary};
@define-color link_visited_color      {primary};
"#,
        base      = p.base,
        mantle    = p.mantle,
        crust     = p.crust,
        surface0  = p.surface0,
        surface1  = p.surface1,
        surface2  = p.surface2,
        text      = p.text,
        subtext1  = p.subtext1,
        subtext0  = p.subtext0,
        primary   = p.primary,
        secondary = p.secondary,
        tertiary  = p.tertiary,
        error     = p.error,
        warning   = p.warning,
        info      = p.info,
        overlay0  = p.overlay0,
        overlay1  = p.overlay1,
        overlay2  = p.overlay2,
    )
}

async fn write_to(gtk_dir: &str, css: &str) -> Result<(), ThemeError> {
    let config_home = dirs::config_dir()
        .ok_or_else(|| ThemeError::Writer("cannot determine config dir".into()))?;

    let dir = config_home.join(gtk_dir);
    tokio::fs::create_dir_all(&dir).await?;

    let colors_path = dir.join("colors.css");
    tokio::fs::write(&colors_path, css).await?;

    // Ensure gtk.css imports colors.css — create it if missing, append import if needed
    let gtk_css_path = dir.join("gtk.css");
    let import_line  = "@import 'colors.css';\n";

    if gtk_css_path.exists() {
        let existing = tokio::fs::read_to_string(&gtk_css_path).await.unwrap_or_default();
        if !existing.contains("@import 'colors.css'") {
            // Prepend the import to the existing file
            let new_content = format!("{import_line}{existing}");
            tokio::fs::write(&gtk_css_path, new_content).await?;
        }
    } else {
        tokio::fs::write(&gtk_css_path, import_line).await?;
    }

    Ok(())
}
