/// writers/shell.rs
///
/// Writes palette colors as shell environment variables.
///
/// Output: ~/.config/crawl/theme.sh
///
/// Source this in your .zshrc / .bashrc for scripts that need palette colors:
///
///   # ~/.zshrc
///   [ -f "$XDG_CONFIG_HOME/crawl/theme.sh" ] && source "$XDG_CONFIG_HOME/crawl/theme.sh"
///
/// Also writes ~/.config/crawl/theme.zsh with zsh-specific array syntax,
/// useful for Starship/p10k prompt theming or custom prompt scripts.
///
/// Usage in scripts:
///   echo "Primary color: $CRAWL_PRIMARY"
///   notify-send --urgency=low "" "Done" --background "$CRAWL_BASE"

use crate::{palette::Palette, ThemeError};
use tracing::info;

pub async fn write(palette: &Palette) -> Result<(), ThemeError> {
    let sh  = render_sh(palette);
    let zsh = render_zsh(palette);

    let config_home = dirs::config_dir()
        .ok_or_else(|| ThemeError::Writer("cannot determine config dir".into()))?;
    let crawl_dir = config_home.join("crawl");
    tokio::fs::create_dir_all(&crawl_dir).await?;

    tokio::fs::write(crawl_dir.join("theme.sh"), &sh).await?;
    tokio::fs::write(crawl_dir.join("theme.zsh"), &zsh).await?;

    info!("shell: theme.sh and theme.zsh written");
    Ok(())
}

fn render_sh(p: &Palette) -> String {
    format!(
r#"# Generated by crawl-theme — do not edit manually.
# Source: source "$XDG_CONFIG_HOME/crawl/theme.sh"

# ── Surfaces ────────────────────────────────────────────────────────────────
export CRAWL_BASE="{base}"
export CRAWL_MANTLE="{mantle}"
export CRAWL_CRUST="{crust}"
export CRAWL_SURFACE0="{surface0}"
export CRAWL_SURFACE1="{surface1}"
export CRAWL_SURFACE2="{surface2}"

# ── Text ────────────────────────────────────────────────────────────────────
export CRAWL_TEXT="{text}"
export CRAWL_SUBTEXT1="{subtext1}"
export CRAWL_SUBTEXT0="{subtext0}"

# ── Accents ─────────────────────────────────────────────────────────────────
export CRAWL_PRIMARY="{primary}"
export CRAWL_SECONDARY="{secondary}"
export CRAWL_TERTIARY="{tertiary}"
export CRAWL_ERROR="{error}"
export CRAWL_WARNING="{warning}"
export CRAWL_INFO="{info}"

# ── Overlays ─────────────────────────────────────────────────────────────────
export CRAWL_OVERLAY0="{overlay0}"
export CRAWL_OVERLAY1="{overlay1}"
export CRAWL_OVERLAY2="{overlay2}"

# ── Aliases for common usage ──────────────────────────────────────────────────
export CRAWL_BG="$CRAWL_BASE"
export CRAWL_FG="$CRAWL_TEXT"
export CRAWL_ACCENT="$CRAWL_PRIMARY"
export CRAWL_DANGER="$CRAWL_ERROR"
export CRAWL_SUCCESS="$CRAWL_TERTIARY"
"#,
        base      = p.base,      mantle    = p.mantle,    crust     = p.crust,
        surface0  = p.surface0,  surface1  = p.surface1,  surface2  = p.surface2,
        text      = p.text,      subtext1  = p.subtext1,  subtext0  = p.subtext0,
        primary   = p.primary,   secondary = p.secondary, tertiary  = p.tertiary,
        error     = p.error,     warning   = p.warning,   info      = p.info,
        overlay0  = p.overlay0,  overlay1  = p.overlay1,  overlay2  = p.overlay2,
    )
}

fn render_zsh(p: &Palette) -> String {
    // Zsh associative array — useful for prompt scripting and Starship custom modules
    format!(
r#"# Generated by crawl-theme — do not edit manually.
# Usage: source "$XDG_CONFIG_HOME/crawl/theme.zsh"
# Then: echo $crawl[primary]

typeset -A crawl
crawl=(
    base      "{base}"
    mantle    "{mantle}"
    crust     "{crust}"
    surface0  "{surface0}"
    surface1  "{surface1}"
    surface2  "{surface2}"
    text      "{text}"
    subtext1  "{subtext1}"
    subtext0  "{subtext0}"
    primary   "{primary}"
    secondary "{secondary}"
    tertiary  "{tertiary}"
    error     "{error}"
    warning   "{warning}"
    info      "{info}"
    overlay0  "{overlay0}"
    overlay1  "{overlay1}"
    overlay2  "{overlay2}"
)
"#,
        base      = p.base,      mantle    = p.mantle,    crust     = p.crust,
        surface0  = p.surface0,  surface1  = p.surface1,  surface2  = p.surface2,
        text      = p.text,      subtext1  = p.subtext1,  subtext0  = p.subtext0,
        primary   = p.primary,   secondary = p.secondary, tertiary  = p.tertiary,
        error     = p.error,     warning   = p.warning,   info      = p.info,
        overlay0  = p.overlay0,  overlay1  = p.overlay1,  overlay2  = p.overlay2,
    )
}
